In [1]:
import pandas as pd

In [2]:
sch1 = pd.read_csv(r"C:\Users\ELCOT\Desktop\TREE PROJECT\ALL OUR CAMPS\CSV\ST PATRICK'S.csv")

In [3]:
#ST PATRICK'S

In [5]:
sch1.head(5)

        NAME OF TREE SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0           TAMARIND       Tamarindus indica                4
1        BAMBOO TREE        Bambusa vulgaris               19
2          NEEM TREE      Azadirachta indica               16
3        PORTIA TREE      Thespesia populnea                1
4  ASIAN BULLET WOOD         MIMUSOPS ELENGI               16

In [6]:
sch1.tail(5)

          NAME OF TREE SCIENTIFIC NAME OF TREE  NUMBER OF TREES
26     AFRICAN TALISAY      Terminalia Mantaly                8
27  ALEXANDRIAN LAUREL  Calophyllum inophyllum                2
28           COOK PINE    Araucaria columnaris                1
29        BAMBOO CYCAD      Ceratozamia hildae               15
30     ROYAL PALM TREE         Roystonea regia               12

In [7]:
sch1.head(31)

          NAME OF TREE SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0             TAMARIND       Tamarindus indica                4
1          BAMBOO TREE        Bambusa vulgaris               19
2            NEEM TREE      Azadirachta indica               16
3          PORTIA TREE      Thespesia populnea                1
4    ASIAN BULLET WOOD         MIMUSOPS ELENGI               16
5          ALMOND TREE           Prunus dulcis                5
6         TECTONA TREE         Tectona grandis                3
7         COCONUT TREE          Cocos nucifera                9
8          BANANA TREE                    Musa               12
9        RAMBUTAN TREE     Nephelium lappaceum                1
10         ORCHID TREE      Bauhinia variegata                9
11       FISHTAIL PALM                 Caryota               13
12           PALM TREE               Arecaceae                8
13   INDIAN BEECH TREE       Millettia pinnata               22
14     MONKEY POD TREE           Samanea saman               17
15        AMALTAS TREE          Cassia fistula                1
16          ASHOK TREE            Saraca asoca               39
17          MANGO TREE        Mangifera indica               14
18         SAPOTA TREE        Manilkara zapota                5
19       GULMOHAR TREE           Delonix regia               12
20            CAPE FIG          Ficus capensis                7
21          GUAVA TREE         Psidium guajava                4
22          JAMUN TREE         Syzygium cumini                1
23     CHILEAN JASMINE         Mandevilla laxa                3
24       OLEANDER TREE         Nerium oleander                1
25      CHRISTMAS TREE    Araucaria columnariS                3
26     AFRICAN TALISAY      Terminalia Mantaly                8
27  ALEXANDRIAN LAUREL  Calophyllum inophyllum                2
28           COOK PINE    Araucaria columnaris                1
29        BAMBOO CYCAD      Ceratozamia hildae               15
30     ROYAL PALM TREE         Roystonea regia               12

In [8]:
#ST MICHAELS

In [9]:
sch2 = pd.read_csv(r"C:\Users\ELCOT\Desktop\TREE PROJECT\ALL OUR CAMPS\CSV\ST MICHAELS.csv")

In [10]:
sch2.head(5)

          TREES NAME SCIENTIFIC NAME OF  TREE  TREES COUNT
0        BAMBOO TREE       Ceratozamia hildae            4
1          PALM TREE                Arecaceae            7
2    SACRED FIG TREE          Ficus religiosa            2
3         ASHOK TREE             Saraca asoca           17
4  Asian Bullet Wood          MIMUSOPS ELENGI            7

In [11]:
sch2.tail(5)

         TREES NAME SCIENTIFIC NAME OF  TREE  TREES COUNT
15  ROYAL PALM TREE          Roystonea regia           17
16      PAPAYA TREE            Carica papaya            5
17             PINE         Pinus roxburghii            2
18      SAPOTA TREE         Manilkara zapota            2
19  MONKEY POD TREE            Samanea saman            1

In [12]:
sch2.head(20)

            TREES NAME SCIENTIFIC NAME OF  TREE  TREES COUNT
0          BAMBOO TREE       Ceratozamia hildae            4
1            PALM TREE                Arecaceae            7
2      SACRED FIG TREE          Ficus religiosa            2
3           ASHOK TREE             Saraca asoca           17
4    Asian Bullet Wood          MIMUSOPS ELENGI            7
5    YELLOW ELDER TREE             Tecoma stans            2
6         COCONUT TREE           Cocos nucifera            5
7            NEEM TREE       Azadirachta indica           12
8   FOX TAIL PALM TREE       Wodyetia bifurcata           17
9     BOTTLE PALM TREE   Hyophorbe lagenicaulis            9
10  ALEXANDRIAN LAUREL   Calophyllum inophyllum            8
11        TECTONA TREE          Tectona grandis           20
12        BANANA TREE                      Musa            5
13   INDIAN BEECH TREE        Millettia pinnata            6
14         ALMOND TREE            Prunus dulcis            7
15     ROYAL PALM TREE          Roystonea regia           17
16         PAPAYA TREE            Carica papaya            5
17                PINE         Pinus roxburghii            2
18         SAPOTA TREE         Manilkara zapota            2
19     MONKEY POD TREE            Samanea saman            1

In [13]:
#ICSE

In [14]:
sch3 = pd.read_csv(r"C:\Users\ELCOT\Desktop\TREE PROJECT\ALL OUR CAMPS\CSV\ICSE.csv")

In [15]:
sch3.head(5)

         TREES NAME  SCIENTIFIC NAME OF TREES   TREES COUNT
0  INDIAN BEECH TREE         Millettia pinnata            7
1    MONKEY POD TREE             Samanea saman            3
2          NEEM TREE        Azadirachta indica            5
3        ALMOND TREE             Prunus dulcis            3
4       BAMBOO CYCAD        Ceratozamia hildae           16

In [16]:
sch3.tail(5)

     TREES NAME  SCIENTIFIC NAME OF TREES   TREES COUNT
4   BAMBOO CYCAD        Ceratozamia hildae           16
5     ASHOK TREE              Saraca asoca           14
6   TECTONA TREE           Tectona grandis            2
7  GULMOHAR TREE             Delonix regia            1
8           PINE          Pinus roxburghii            1

In [17]:
sch3.head(9)

         TREES NAME  SCIENTIFIC NAME OF TREES   TREES COUNT
0  INDIAN BEECH TREE         Millettia pinnata            7
1    MONKEY POD TREE             Samanea saman            3
2          NEEM TREE        Azadirachta indica            5
3        ALMOND TREE             Prunus dulcis            3
4       BAMBOO CYCAD        Ceratozamia hildae           16
5         ASHOK TREE              Saraca asoca           14
6       TECTONA TREE           Tectona grandis            2
7      GULMOHAR TREE             Delonix regia            1
8               PINE          Pinus roxburghii            1

In [18]:
#A BLOCK COLLEGE

In [19]:
a = pd.read_csv(r"C:\Users\ELCOT\Desktop\TREE PROJECT\ALL OUR CAMPS\CSV\A BLOCK.csv")

In [20]:
a.head(5)

          TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0         MANGO TREE        Mangifera indica                3
1  INDIAN BEECH TREE       Millettia pinnata                4
2  Asian Bullet Wood         MIMUSOPS ELENGI                8
3       COCONUT TREE          Cocos nucifera                9
4          NEEM TREE      Azadirachta indica                1

In [21]:
a.tail(5)

            TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
6             FIG TREE            Ficus carica                1
7            PALM TREE               Arecaceae                6
8             TAMARIND       Tamarindus indica                2
9         BANANA TREE                     Musa                8
10  GOLDEN BAMBOO TREE     Phyllostachys aurea               12

In [22]:
a.head(11)

            TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0           MANGO TREE        Mangifera indica                3
1    INDIAN BEECH TREE       Millettia pinnata                4
2    Asian Bullet Wood         MIMUSOPS ELENGI                8
3         COCONUT TREE          Cocos nucifera                9
4            NEEM TREE      Azadirachta indica                1
5          ALMOND TREE           Prunus dulcis                1
6             FIG TREE            Ficus carica                1
7            PALM TREE               Arecaceae                6
8             TAMARIND       Tamarindus indica                2
9         BANANA TREE                     Musa                8
10  GOLDEN BAMBOO TREE     Phyllostachys aurea               12

In [23]:
#B BLOCK COLLEGE

In [24]:
b = pd.read_csv(r"C:\Users\ELCOT\Desktop\TREE PROJECT\ALL OUR CAMPS\CSV\B BLOCK.csv")

In [25]:
b.head(5)

    TREES NAME     SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0       ACACIA                genus Acacia                3
1     HAINANIA  Hainania trichosperma Merr                4
2  BANANA TREE                        Musa                7
3  PAPAYA TREE               Carica papaya                2
4    NEEM TREE          Azadirachta indica                5

In [26]:
b.tail(5)

           TREES NAME   SCIENTIFIC NAME OF TREE  NUMBER OF TREES
10     CHRISTMAS TREE      Araucaria columnariS                1
11  BIRD CATCHER TREE           Pisonia grandis                1
12      GULMOHAR TREE             Delonix regia                2
13     JACKFRUIT TREE  Artocarpus heterophyllus                1
14  STERCULIA FOETIDA                 Sterculia                1

In [27]:
b.head(15)

           TREES NAME     SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0              ACACIA                genus Acacia                3
1            HAINANIA  Hainania trichosperma Merr                4
2         BANANA TREE                        Musa                7
3         PAPAYA TREE               Carica papaya                2
4           NEEM TREE          Azadirachta indica                5
5         ALMOND TREE               Prunus dulcis                2
6     MONKEY POD TREE               Samanea saman                1
7        COCONUT TREE              Cocos nucifera                3
8   INDIAN BEECH TREE           Millettia pinnata                5
9          ASHOK TREE                Saraca asoca                1
10     CHRISTMAS TREE        Araucaria columnariS                1
11  BIRD CATCHER TREE             Pisonia grandis                1
12      GULMOHAR TREE               Delonix regia                2
13     JACKFRUIT TREE    Artocarpus heterophyllus                1
14  STERCULIA FOETIDA                   Sterculia                1

In [28]:
#C BLOCK COLLEGE

In [29]:
C = pd.read_csv(r"C:\Users\ELCOT\Desktop\TREE PROJECT\ALL OUR CAMPS\CSV\C BLOCK.csv")

In [30]:
C.head(5)

          TREES NAME   SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0     JACKFRUIT TREE  Artocarpus heterophyllus                4
1  INDIAN BEECH TREE         Millettia pinnata                5
2         MANGO TREE          Mangifera indica                7
3         GUAVA TREE           Psidium guajava                3
4       COCONUT TREE            Cocos nucifera               13

In [31]:
C.tail(5)

         TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
11  MONKEY POD TREE           Samanea saman                1
12      ALMOND TREE           Prunus dulcis                1
13       ASHOK TREE            Saraca asoca                1
14      SAPOTA TREE        Manilkara zapota                1
15    CONIFER TREE                Pinophyta                3

In [32]:
C.head(16)

             TREES NAME   SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0        JACKFRUIT TREE  Artocarpus heterophyllus                4
1     INDIAN BEECH TREE         Millettia pinnata                5
2            MANGO TREE          Mangifera indica                7
3            GUAVA TREE           Psidium guajava                3
4          COCONUT TREE            Cocos nucifera               13
5             NEEM TREE        Azadirachta indica                2
6           PAPAYA TREE             Carica papaya                1
7           BANANA TREE                      Musa               18
8     BRID CATCHER TREE           Pisonia grandis                4
9       ROYAL PALM TREE           Roystonea regia               10
10  CHRISTMAS PALM TREE        Adonidia merrillii                3
11      MONKEY POD TREE             Samanea saman                1
12          ALMOND TREE             Prunus dulcis                1
13           ASHOK TREE              Saraca asoca                1
14          SAPOTA TREE          Manilkara zapota                1
15        CONIFER TREE                  Pinophyta                3

In [33]:
#D BLOCK COLLEGE

In [34]:
D = pd.read_csv(r"C:\Users\ELCOT\Desktop\TREE PROJECT\ALL OUR CAMPS\CSV\D BLOCK.csv")

In [35]:
D.head(3)

           TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0        COCONUT TREE           Prunus dulcis              NaN
1          MANGO TREE        Mangifera indica              NaN
2  AFRICAN TULIP TREE   Spathodea campanulata              NaN

In [36]:
D.tail(3)

           TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0        COCONUT TREE           Prunus dulcis              NaN
1          MANGO TREE        Mangifera indica              NaN
2  AFRICAN TULIP TREE   Spathodea campanulata              NaN

In [37]:
D.head(3)

           TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0        COCONUT TREE           Prunus dulcis              NaN
1          MANGO TREE        Mangifera indica              NaN
2  AFRICAN TULIP TREE   Spathodea campanulata              NaN

In [38]:
#E BLOCK COLLEGE

In [39]:
E = pd.read_csv(r"C:\Users\ELCOT\Desktop\TREE PROJECT\ALL OUR CAMPS\CSV\E BLOCK.csv")

In [40]:
E.head(5)

          TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0         ASHOK TREE            Saraca asoca               13
1          NEEM TREE      Azadirachta indica                4
2        ALMOND TREE           Prunus dulcis                1
3    ROYAL PALM TREE         Roystonea regia                4
4  INDIAN BEECH TREE       Millettia pinnata                5

In [41]:
E.tail(5)

           TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
4   INDIAN BEECH TREE       Millettia pinnata                5
5   YELLOW ELDER TREE            Tecoma stans                1
6  GOLDEN BAMBOO TREE     Phyllostachys aurea               25
7     MONKEY POD TREE           Samanea saman                6
8       GULMOHAR TREE           Delonix regia                3

In [42]:
E.head(9)

           TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0          ASHOK TREE            Saraca asoca               13
1           NEEM TREE      Azadirachta indica                4
2         ALMOND TREE           Prunus dulcis                1
3     ROYAL PALM TREE         Roystonea regia                4
4   INDIAN BEECH TREE       Millettia pinnata                5
5   YELLOW ELDER TREE            Tecoma stans                1
6  GOLDEN BAMBOO TREE     Phyllostachys aurea               25
7     MONKEY POD TREE           Samanea saman                6
8       GULMOHAR TREE           Delonix regia                3

In [43]:
#PARKING COLLEGE

In [44]:
PARKING = pd.read_csv(r"C:\Users\ELCOT\Desktop\TREE PROJECT\ALL OUR CAMPS\CSV\PARKING.csv")

In [45]:
PARKING.head(5)

          TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0         ASHOK TREE            Saraca asoca                2
1          NEEM TREE      Azadirachta indica                2
2        ALMOND TREE           Prunus dulcis                4
3  Asian Bullet Wood         MIMUSOPS ELENGI                3
4    SACRED FIG TREE         Ficus religiosa                2

In [46]:
PARKING.tail(5)

           TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
5   INDIAN BEECH TREE       Millettia pinnata                5
6        COCONUT TREE          Cocos nucifera                2
7         SAPOTA TREE        Manilkara zapota                1
8  CUSTARD APPLE TREE         Annona squamosa                1
9  GOLDEN BAMBOO TREE     Phyllostachys aurea               28

In [47]:
PARKING.head(10)

           TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREES
0          ASHOK TREE            Saraca asoca                2
1           NEEM TREE      Azadirachta indica                2
2         ALMOND TREE           Prunus dulcis                4
3   Asian Bullet Wood         MIMUSOPS ELENGI                3
4     SACRED FIG TREE         Ficus religiosa                2
5   INDIAN BEECH TREE       Millettia pinnata                5
6        COCONUT TREE          Cocos nucifera                2
7         SAPOTA TREE        Manilkara zapota                1
8  CUSTARD APPLE TREE         Annona squamosa                1
9  GOLDEN BAMBOO TREE     Phyllostachys aurea               28

In [48]:
#GROUND

In [49]:
G = pd.read_csv(r"C:\Users\ELCOT\Desktop\TREE PROJECT\ALL OUR CAMPS\CSV\GROUND.csv")

In [50]:
G.head(5)

          TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREE
0          NEEM TREE      Azadirachta indica              30
1        ALMOND TREE           Prunus dulcis               4
2  YELLOW ELDER TREE            Tecoma stans               1
3           TAMARIND       Tamarindus indica               3
4         MANGO TREE        Mangifera indica               2

In [51]:
G.tail(5)

           TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREE
10    MONKEY POD TREE           Samanea saman               9
11       TECTONA TREE         Tectona grandis               9
12  INDAIN BEECH TREE       Millettia pinnata              20
13  Asian Bullet Wood         MIMUSOPS ELENGI               4
14  STERCULIA FOETIDA               Sterculia               1

In [52]:
G.head(15)

           TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREE
0           NEEM TREE      Azadirachta indica              30
1         ALMOND TREE           Prunus dulcis               4
2   YELLOW ELDER TREE            Tecoma stans               1
3            TAMARIND       Tamarindus indica               3
4          MANGO TREE        Mangifera indica               2
5         ASHOKA TREE            Saraca asoca              23
6     SACRED FIG TREE         Ficus religiosa               1
7          GUAVA TREE         Psidium guajava               1
8        COCONUT TREE          Cocos nucifera               1
9       GULMOHAR TREE           Delonix regia               6
10    MONKEY POD TREE           Samanea saman               9
11       TECTONA TREE         Tectona grandis               9
12  INDAIN BEECH TREE       Millettia pinnata              20
13  Asian Bullet Wood         MIMUSOPS ELENGI               4
14  STERCULIA FOETIDA               Sterculia               1

In [53]:
#ourcampus

In [59]:
ourcampus = pd.read_csv(r"C:\Users\ELCOT\Desktop\TREE PROJECT\ALL OUR CAMPS\CSV\ourcampus.csv")

In [60]:
ourcampus.head(5)

          TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREE
0          NEEM TREE      Azadirachta indica              77
1  INDIAN BEECH TREE       Millettia pinnata              79
2    MONKEY POD TREE           Samanea saman              38
3        ALMOND TREE           Prunus dulcis              28
4       BAMBOO CYCAD      Ceratozamia hildae              31

In [61]:
ourcampus.tail(5)

             TREES NAME SCIENTIFIC NAME OF TREE  NUMBER OF TREE
43        CONIFER TREE                Pinophyta               3
44   AFRICAN TULIP TREE   Spathodea campanulata               2
45   CUSTARD APPLE TREE         Annona squamosa               1
46  CHRISTMAS PALM TREE      Adonidia merrillii               3
47    YELLOW ELDER TREE            Tecoma stans               4

In [62]:
ourcampus.head(49)

             TREES NAME     SCIENTIFIC NAME OF TREE  NUMBER OF TREE
0             NEEM TREE          Azadirachta indica              77
1     INDIAN BEECH TREE           Millettia pinnata              79
2       MONKEY POD TREE               Samanea saman              38
3           ALMOND TREE               Prunus dulcis              28
4          BAMBOO CYCAD          Ceratozamia hildae              31
5            ASHOK TREE                Saraca asoca             110
6          TECTONA TREE             Tectona grandis              34
7           ORCHID TREE          Bauhinia variegata               9
8         RAMBUTAN TREE         Nephelium lappaceum               1
9     STERCULIA FOETIDA                   Sterculia               2
10          PORTIA TREE          Thespesia populnea               1
11        GULMOHAR TREE               Delonix regia              24
12                 PINE            Pinus roxburghii               3
13          BAMBOO TREE         Phyllostachys aurea              23
14            PALM TREE                   Arecaceae              21
15      SACRED FIG TREE             Ficus religiosa               5
16    Asian Bullet Wood             MIMUSOPS ELENGI              38
17   ALEXANDRIAN LAUREL      Calophyllum inophyllum              10
18         COCONUT TREE              Cocos nucifera              43
19   FOX TAIL PALM TREE          Wodyetia bifurcata              17
20     BOTTLE PALM TREE      Hyophorbe lagenicaulis               9
21          BANANA TREE                        Musa              50
22      ROYAL PALM TREE             Roystonea regia              43
23          PAPAYA TREE               Carica papaya               8
24          SAPOTA TREE            Manilkara zapota               9
25             TAMARIND           Tamarindus indica               9
26           MANGO TREE            Mangifera indica              27
27           GUAVA TREE             Psidium guajava               8
28        FISHTAIL PALM                     Caryota              13
29             CAPE FIG              Ficus capensis               7
30           JAMUN TREE             Syzygium cumini               1
31      CHILEAN JASMINE             Mandevilla laxa               3
32        OLEANDER TREE             Nerium oleander               1
33       CHRISTMAS TREE        Araucaria columnariS               4
34      AFRICAN TALISAY          Terminalia Mantaly               8
35            COOK PINE        Araucaria columnaris               1
36         AMALTAS TREE              Cassia fistula               1
37             FIG TREE                Ficus carica               1
38   GOLDEN BAMBOO TREE         Phyllostachys aurea              65
39               ACACIA                genus Acacia               3
40             HAINANIA  Hainania trichosperma Merr               4
41    BIRD CATCHER TREE             Pisonia grandis               5
42       JACKFRUIT TREE    Artocarpus heterophyllus               5
43        CONIFER TREE                    Pinophyta               3
44   AFRICAN TULIP TREE       Spathodea campanulata               2
45   CUSTARD APPLE TREE             Annona squamosa               1
46  CHRISTMAS PALM TREE          Adonidia merrillii               3
47    YELLOW ELDER TREE                Tecoma stans               4